FROM node:20-alpine

EXPOSE 3000

ARG NEXT_PUBLIC_API_NLP
ARG NEXT_PUBLIC_API_RECOMMENDER
ARG NEXT_PUBLIC_API_SERVICE
ARG NEXT_PUBLIC_NUWA_HOST
ARG NEXT_PUBLIC_WARP_BASEURL
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_GOOGLE_LINK
ARG NEXT_PUBLIC_WOOLWORLDS_HOST
ARG NEXT_PUBLIC_WOOLWORLDS_APIKEY

WORKDIR /app

COPY . .

RUN corepack enable
RUN pnpm i
RUN pnpm exec next telemetry disable
RUN pnpm build
CMD ["pnpm", "start"]
