version: "3.9"

services:
  wd-enterprise-ui:
    container_name: enterprise
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        buildno: 0.0.1
        NEXT_PUBLIC_API_NLP: "https://nlp.warpdriven.ai/latest"
        NEXT_PUBLIC_API_RECOMMENDER: "https://recommender.warpdriven.ai/latest"
        NEXT_PUBLIC_API_SERVICE: "https://auth.warpdriven.ai"
        NEXT_PUBLIC_GOOGLE_LINK: "https://accounts.google.com/o/oauth2/v2/auth?response_type=token&client_id=118160730599-pjl4sdkp0dfaso943bc4g5lp1d6b61ba.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Ferp.warpdriven.ai%2Fauth_oauth%2Fsignin&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&state=%7B%22d%22%3A+%22wd-erp%22%2C+%22p%22%3A+3%2C+%22r%22%3A+%22https%253A%252F%252Ferp.warpdriven.ai%252Fsubscription%252Fvs%253F%22%7D"
        NEXT_PUBLIC_NUWA_HOST: "https://nuwa.warpdriven.ai/latest"
        NEXT_PUBLIC_POSTHOG_HOST: "https://app.posthog.com"
        NEXT_PUBLIC_POSTHOG_KEY: "phc_2V3pFtd6J4vhzQzU9SVmJH8j0Ku5Ew9ysZmul02zQE"
        NEXT_PUBLIC_WARP_BASEURL: "https://erp.warpdriven.ai/"
        NEXT_PUBLIC_WOOLWORLDS_HOST: "https://woolworlds.com/isc"
        NEXT_PUBLIC_WOOLWORLDS_APIKEY: "ac62ce3a528ca4292498971aa5e197ac9b75d28f"

    image: wd.enterprise.ui
    hostname: enterprise
    deploy:
      resources:
        limits:
          memory: 1000M

    restart: always
    networks:
      wd_ai_net:
        ipv4_address: 172.18.0.11

networks:
  wd_ai_net:
    external: true
